[package]
name = "rust-auth"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = "0.5"
diesel = { version = "1.4", features = ["postgres", "r2d2-diesel"] }
serde = { version = "1.0", features = ["derive"] }
argon2 = "0.11"
jsonwebtoken = "8"